
import sys
import wx

GUI_WINDOW_VARIANT = wx.WINDOW_VARIANT_NORMAL
ENFORCE_SYSTEM_FONT = True
#BACKGROUND_COLOUR = 'white'
#BACKGROUND_COLOUR = '#B5CEDF'
BACKGROUND_COLOUR = '#F8F7EF'
BACKGROUND_TEXTBOX_NOTFILLED = '#FCDFFF'
if sys.platform == 'darwin':
    GUI_WINDOW_VARIANT = wx.WINDOW_VARIANT_SMALL
    ENFORCE_SYSTEM_FONT = True


